using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace DatingApp.API.Entities
{
    // FcmToken can only exist as a child of User
    [Owned]
    public class FcmToken
    {
        // Explicit set Id as primary key to avoid error from composite primary key generated by EF Core which consists of this Id and User's Id
        [Key]
        public int Id { get; set; }
        public User User { get; set; }
        public string Token { get; set; }
    }
}
