using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace DatingApp.API.Entities
{
    // RefreshToken can only exist as a child of User
    [Owned]
    public class RefreshToken
    {
        // Explicit set Id as primary key to avoid error from composite primary key generated by EF Core which consists of this Id and User's Id
        [Key]
        public int Id { get; set; }

        public User User { get; set; }

        public string Token { get; set; }

        public DateTime Expires { get; set; }

        public bool IsExpired => DateTime.Now >= Expires;

        public DateTime Created { get; set; }

        public string CreatedByIp { get; set; }

        public string Device { get; set; }

        public string Application { get; set; }

        public string Location { get; set; }

        public DateTime LastActive { get; set; }

        //public DateTime? Revoked { get; set; }

        //public string RevokedByIp { get; set; }

        //public string ReplaceByToken { get; set; }

        //public bool IsActive => Revoked == null && !IsExpired;
    }
}
